version: 1

before:
  hooks:
  # You may remove this if you don't use go modules.
  - go mod tidy
  # you may remove this if you don't need go generate
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
archives:
- id: release-format
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^ci:"
