name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branch: 
    - main

jobs:
  kind:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: engineerd/setup-kind@v0.5.0
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system