name: e2e

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

jobs:
  kind:
    name: e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        passenger-version:
        - 6.0.18
        - 6.0.19
        - 6.0.20
    steps:
    - uses: actions/checkout@v4
    - uses: helm/kind-action@v1
      with:
        cluster_name: kind
    - run: |
        kind version
        kubectl cluster-info
        kubectl get nodes -o wide

    - name: Kind Load Image
      run: |
        docker build -t passenger-go-exporter:test .
        kind load docker-image passenger-go-exporter:test
    - name: Testing
      run: |
        export PASSENGER_VERSION=${{ matrix.passenger-version }}
        ./test/kubernetes/run.sh
